class IntegralVC:
    """
      Class to implement Integral Programming Algorithm for Vertex Cover
    """

    def vc_integral(self, graph):
        """
          Method to identify the vertex cover and cost generated by the Integral Programming Algorithm
          Parameter:
            Graph 
          Return:
            Vertex cost of the vertex cover identified.
          Logic:
            Have a varaible for each list that can have values either 0 or 1
            Iterate through all the edges
              Check for the constraints for each edge Eg: e1(x1, x2) then check X1+X2>=1
              If the condition is not passed then assign one of the vertex variable to 1
              Goal is to minimize the total cost, so assign 1 to the vertex with low vertex cost.
            Vertex Cover is the vertices that has a variable with value 1
        """
        vc_result = []
        vc_variable = [0 for i in range(len(graph.nodes))]
        for e in graph.edges:
            from_vertex = e[0]
            to_vertex = e[1]
            if (vc_variable[from_vertex] + vc_variable[to_vertex]) >= 1:
                continue
            if graph.nodes[from_vertex]["cost"] < graph.nodes[to_vertex]["cost"]:
                vc_variable[from_vertex] = 1
                vc_result.append(from_vertex)
            else:
                vc_variable[to_vertex] = 1
                vc_result.append(to_vertex)
        # print(vc_result)
        vc_cost = 0
        for i in vc_result:
            vc_cost += graph.nodes[i]["cost"]
        return vc_cost